version: "3.3"
services:
  app:
    build:
      args:
        user: wiseass
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: rpg
    restart: unless-stopped
    working_dir: /var/www/
    environment:
        APP_NAME: ${APP_NAME}
        APP_ENV: ${APP_ENV}
        APP_KEY: ${APP_KEY}
        APP_DEBUG: ${APP_DEBUG}
        APP_URL: ${APP_URL}
        ASSET_URL: ${ASSET_URL}
        LOG_CHANNEL: ${LOG_CHANNEL}
        LOG_LEVEL: ${LOG_LEVEL}
        DB_CONNECTION: ${DB_CONNECTION}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        BROADCAST_DRIVER: ${BROADCAST_DRIVER}
        CACHE_DRIVER: ${CACHE_DRIVER}
        FILESYSTEM_DRIVER: ${FILESYSTEM_DRIVER}
        QUEUE_CONNECTION: ${QUEUE_CONNECTION}
        SESSION_DRIVER: ${SESSION_DRIVER}
        SESSION_LIFETIME: ${SESSION_LIFETIME}
    volumes:
      - ./:/var/www
    networks:
      - rpg
  # vite:
  #  build:
  #     context: ./
  #     dockerfile: DockerfileVite
  #  container_name: vite
  #  entrypoint: /bin/sh
  #  working_dir: /srv/app
  #  restart: unless-stopped
  #  ports:
  #   - 3001:80
  #  volumes:
  #    - type: bind
  #      source: ./
  #      target: /srv/app
  #  tty: true
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - rpg
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
        - 'mongodb:/data/db'
    ports:
        - ${DB_PORT}:27017
    networks:
      - rpg

networks:
  rpg:
    driver: bridge

volumes:
  mongodb:
    driver: local
